### ISSUE TITLE
GUI character translation missing and incomplete

### ISSUE THREAD

**Issue by wcxu21** [rayenghanmi/RyTuneX#11]
Hi, thank you for adding Chinese language. I downloaded the software and tested it, and I found that parts of the interface in the app still had a lot of untranslated parts.

For example, there are still missing characters in the function names and introductions on the right side of the function tab: system optimization, privacy, Windows functions, and drives under system information. It still displays English under the Chinese system.

This is a bit unfriendly to the app experience, and I hope you can take some time to polish the language character text.

Thank you for your work, waiting for the new version to be perfected, I will recommend it to more users in China.
：-）

**Comment by rayenghanmi** [comment]
> Hi, thank you for adding Chinese language. I downloaded the software and tested it, and I found that parts of the interface in the app still had a lot of untranslated parts.
> 
> For example, there are still missing characters in the function names and introductions on the right side of the function tab: system optimization, privacy, Windows functions, and drives under system information. It still displays English under the Chinese system.
> 
> This is a bit unfriendly to the app experience, and I hope you can take some time to polish the language character text.
> 
> Thank you for your work, waiting for the new version to be perfected, I will recommend it to more users in China. ：-）

That's the aim for the next version `polishing translation`, and thx for the recommendation.

**Comment by rayenghanmi** [comment]
@wcxu21 If you can, translate the [en-us file](https://github.com/rayenghanmi/RyTuneX/tree/testing/Strings) into simplified Chinese so the next version gets a full UI translation.
Don't forget to PR into testing branch

And thx

**Comment by wcxu21** [comment]
Thanks for your work, I have re-translated the Chinese content.
