### ISSUE TITLE
[QUESTION] is this program more capable than chris titus windows optimization utility or similar popular windows optimization program available on github?

### ISSUE THREAD

**Issue by HakaishinShwet** [rayenghanmi/RyTuneX#13]
chris titus win util tool - https://github.com/ChrisTitusTech/winutil   is pretty impressive already and this projects look similar to it but doesnt have that many features so are you trying to achieve something different ? if not then what is the purpose of same type of program ? No hate on this but just wanted to ask because if you also trying to create similar thing which i and many can see then i dont think there is point in that.Rather then creating similar one it would be better if you become contributor in that project and help it develop more.Already some are doing great contributions there so thats why i thought if one more contributor can be added in that then it would develop at much faster rate.Rest your wish :-))

**Comment by rayenghanmi** [comment]
> chris titus win util tool - https://github.com/ChrisTitusTech/winutil is pretty impressive already and this projects look similar to it but doesnt have that many features so are you trying to achieve something different ? if not then what is the purpose of same type of program ? No hate on this but just wanted to ask because if you also trying to create similar thing which i and many can see then i dont think there is point in that.Rather then creating similar one it would be better if you become contributor in that project and help it develop more.Already some are doing great contributions there so thats why i thought if one more contributor can be added in that then it would develop at much faster rate.Rest your wish :-))

I've been asked the same question, I'm trying to make a different thing, I'm aiming at making some other features, CTT's winutil is cool, but I wanted also to make mine with some differences, the only problem I'm facing is the lack of time, but soon I'll finish my exams and I'll have more free time to focus on this project.
I hope that I've answered your question.

**Comment by HakaishinShwet** [comment]
@rayenghanmi Cool .I have seen some similar programs so was just curious about that uniqueness part.Maybe you can share your detailed roadmap/plan with which people will know what all things will be different so it will help users to understand and for you too it will be beneficial. ANyways All the best :-)

**Comment by rayenghanmi** [comment]
> ya this program is quite similar to [optimizer](https://github.com/hellzerg/optimizer) by hellzerg but rytunex ui is refreshing and easy to follow although i got [404](https://rayenghanmi.github.io/rytunex/performance.html) error when trying to open learn more about tweak

I've removed those web pages as I'm working on more detailed ones.
