### ISSUE TITLE
The site with detailed disabled details won't open

### ISSUE THREAD

**Issue by 200433zc** [rayenghanmi/RyTuneX#15]
https://rayenghanmi.github.io/rytunex/basic.html
![CopyQ HNFGSS](https://github.com/rayenghanmi/RyTuneX/assets/62494140/24a6d336-01bb-4032-bc4e-38855e0da902)

https://rayenghanmi.github.io/rytunex/performance.html

**Comment by rayenghanmi** [comment]
> https://rayenghanmi.github.io/rytunex/basic.html ![CopyQ HNFGSS](https://private-user-images.githubusercontent.com/62494140/331848437-24a6d336-01bb-4032-bc4e-38855e0da902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTkyNDEsIm5iZiI6MTcxNjA5ODk0MSwicGF0aCI6Ii82MjQ5NDE0MC8zMzE4NDg0MzctMjRhNmQzMzYtMDFiYi00MDMyLWJjNGUtMzg4NTVlMGRhOTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA2MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZjUxN2I3ZGY5N2E2Yzk3YjRkNGE1NDIyY2VhY2ZiZjFmMzRhMDNiZDRmNzhhY2UzOTI0ODJkMjgwNDMzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eXGaG_hzCItilpHrB9m8FeQnjlY8vAB6YtJvYhJPjy0)
> 
> https://rayenghanmi.github.io/rytunex/performance.html

I'm still polishing it. It'll be available soon.
