### ISSUE TITLE
色彩标记

### ISSUE THREAD

**Issue by ouyang7923** [rayenghanmi/RyTuneX#17]
推荐 项建议使用绿色
不推荐 建议使用红色区分
当前 详细了解被禁用的内容 打开是404

**Comment by rayenghanmi** [comment]
> 推荐 项建议使用绿色 不推荐 建议使用红色区分 当前 详细了解被禁用的内容 打开是404

I'll consider your suggestions.
About the 404 error, I'm improving the website, that's why there are no pages. It should be ready soon.

**Comment by rayenghanmi** [comment]
@ouyang7923 
It should be available now. All of the docs pages are available.
