### ISSUE TITLE
After turning on the Disable Telemetry Services option, will "Managed by your organization" be displayed under Edge Settings?

### ISSUE THREAD

**Issue by yoyoyoyolol** [rayenghanmi/RyTuneX#19]
Is the option "Managed by your organization" displayed because of using RyTuneX?

**Comment by rayenghanmi** [comment]
> Is the option "Managed by your organization" displayed because of using RyTuneX?
> 

Yes it is, because that option also disables some of Microsoft Edge's telemetry.

**Comment by yoyoyoyolol** [comment]
> > Is the option "Managed by your organization" displayed because of using RyTuneX?
> 
> Yes it is, because that option also disables some of Microsoft Edge's telemetry.

Got it, thanks for your reply
