### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by xRUSSELL** [rayenghanmi/RyTuneX#2]
As soon as I turn on the first performance optimization option, the app crashes.

**Comment by rayenghanmi** [comment]
> As soon as I turn on the first performance optimization option, the app crashes.

Make sure to run it as admin

**Comment by rayenghanmi** [comment]
Don't use it:
https://twitter.com/PC_Focus_/status/1741794467047182546
use [Chris Titus Tech's Windows Utility](https://github.com/ChrisTitusTech/winutil) instead, because he's well known,
don't download my app, people say it's a malware!
