### ISSUE TITLE
Japanese language file

### ISSUE THREAD

**Issue by coolvitto** [rayenghanmi/RyTuneX#20]
I added the Japanese language file here, is this the correct location?
https://github.com/rayenghanmi/RyTuneX/compare/main...coolvitto:RyTuneX:patch-1

Japanese language file
[ja-jp.zip](https://github.com/user-attachments/files/18141941/ja-jp.zip)

**Comment by rayenghanmi** [comment]
> I added the Japanese language file here, is this the correct location? [main...coolvitto:RyTuneX:patch-1](https://github.com/rayenghanmi/RyTuneX/compare/main...coolvitto:RyTuneX:patch-1)
> 
> Japanese language file [ja-jp.zip](https://github.com/user-attachments/files/18141941/ja-jp.zip)

Create a pull request in the testing branch using the same structure as this example:
![image](https://github.com/user-attachments/assets/f843f318-2d1b-47e4-b1c4-ee856ebb9072)

A folder named `ja-jp` with the changed `Resources.resw` inside the `Strings` folder in the `testing` branch.

**Comment by coolvitto** [comment]
Click "Pull requests"
![sshot-9](https://github.com/user-attachments/assets/bc3630de-bf44-4741-b0ba-3fc0fa52a3f5)
This will be the writing screen,
![sshot-8](https://github.com/user-attachments/assets/68e5656b-947b-46a5-888f-b1be909f83d3)

How do I create a folder?
Strings - ja-jp

**Comment by rayenghanmi** [comment]
> Click "Pull requests" ![sshot-9](https://private-user-images.githubusercontent.com/160416811/395935887-bc3630de-bf44-4741-b0ba-3fc0fa52a3f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjg3MjUsIm5iZiI6MTczNDMyODQyNSwicGF0aCI6Ii8xNjA0MTY4MTEvMzk1OTM1ODg3LWJjMzYzMGRlLWJmNDQtNDc0MS1iMGJhLTNmYzBmYTUyYTNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNTUzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjQ1NTE5NjFiZjgyYjYzMTM0MTMzYTYxMWZjZjI5ZGEwM2IwOGRiYmU2NmM0YWE2NWFlOGFkNjE4YTQwODM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N2NHvUPj7ol6DITjFx3xjGTjWylm00E5z6xwilrETxQ) This will be the writing screen, ![sshot-8](https://private-user-images.githubusercontent.com/160416811/395936078-68e5656b-947b-46a5-888f-b1be909f83d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjg3MjUsIm5iZiI6MTczNDMyODQyNSwicGF0aCI6Ii8xNjA0MTY4MTEvMzk1OTM2MDc4LTY4ZTU2NTZiLTk0N2ItNDZhNS04ODhmLWIxYmU5MDlmODNkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNTUzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjJkZDMyOTZlMzAwOGUyMGRjM2UwMDRhMmZhN2ZmMzA0NmM5NjhhMTgxNzRkNzg4YjA4MzU3NTg0N2Q4YzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ol7fA2xYZE4dWYhdiY1ALx6F3Xd1eCm3ZzvCloCbSzY)
> 
> How do I create a folder? Strings - ja-jp

create it on your desktop or wherever you want, and the drag and drop it inside the `Add a description` section

**Comment by coolvitto** [comment]
I get an error
![sshot-13](https://github.com/user-attachments/assets/8dfb00d2-63eb-4c74-aee4-467a0871fb71)

**Comment by rayenghanmi** [comment]
> I get an error
> ![sshot-13](https://github.com/user-attachments/assets/8dfb00d2-63eb-4c74-aee4-467a0871fb71)
> 
I'll add it myself and mention you in the next version. There's no need to do it yourself. Thanks anyway

**Comment by coolvitto** [comment]
Thank you.

- - - - - - 
Best regards,
coolvitto

**Comment by rayenghanmi** [comment]
Hi again,
If you could take a look at the file one more time to fix any translation
errors that would be greatly appreciated.


Sincerely,
Rayen

**Comment by coolvitto** [comment]
Ok, I'll check again.
________________________________
差出人: Rayen Ghanmi ***@***.***>
送信日時: 2024年12月20日 6:49
宛先: rayenghanmi/RyTuneX ***@***.***>
CC: coolvitto ***@***.***>; Author ***@***.***>
件名: Re: [rayenghanmi/RyTuneX] Japanese language file (Issue #20)


Hi again,
If you could take a look at the file one more time to fix any translation
errors that would be greatly appreciated.


Sincerely,
Rayen

**Comment by coolvitto** [comment]
At this time, it is not possible to display Japanese, so it is not possible to check the detailed error.
I think this is the best possible content.

________________________________
差出人: Rayen Ghanmi ***@***.***>
送信日時: 2024年12月20日 6:49
宛先: rayenghanmi/RyTuneX ***@***.***>
CC: coolvitto ***@***.***>; Author ***@***.***>
件名: Re: [rayenghanmi/RyTuneX] Japanese language file (Issue #20)


Hi again,
If you could take a look at the file one more time to fix any translation
errors that would be greatly appreciated.


Sincerely,
Rayen
