### ISSUE TITLE
Windows sees this as a virus

### ISSUE THREAD

**Issue by babyhuey** [rayenghanmi/RyTuneX#3]
![image](https://github.com/rayenghanmi/RyTuneX/assets/7751607/68c29e39-b8de-4746-b124-bc29786107b7)

**Comment by rayenghanmi** [comment]
It's not certified, I'm broke to afford one, use [Chris Titus Tech's Windows Utility](https://github.com/ChrisTitusTech/winutil) instead.
even twitter didn't like it:
![Screenshot 2024-01-01 162534](https://github.com/rayenghanmi/RyTuneX/assets/108760398/57bab424-eab2-49f8-95a4-43a63e522ac0)
![Screenshot 2024-01-01 165347](https://github.com/rayenghanmi/RyTuneX/assets/108760398/191867ab-1b75-49cd-8d00-eae974a2db4f)
![Screenshot 2024-01-01 165443](https://github.com/rayenghanmi/RyTuneX/assets/108760398/24b2430f-ec8c-493f-abec-88d2db40f175)
![Screenshot 2024-01-01 165504](https://github.com/rayenghanmi/RyTuneX/assets/108760398/4d047d12-9b0c-42d4-a885-30e84eeece97)

**Comment by rayenghanmi** [comment]
> ![image](https://private-user-images.githubusercontent.com/7751607/293595717-68c29e39-b8de-4746-b124-bc29786107b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzYyMTgsIm5iZiI6MTcwNDQzNTkxOCwicGF0aCI6Ii83NzUxNjA3LzI5MzU5NTcxNy02OGMyOWUzOS1iOGRlLTQ3NDYtYjEyNC1iYzI5Nzg2MTA3YjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMDYyNTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjNhODAxY2EyYzU4ODhmOGJiY2U0ZmE0YzUzMGVlM2MzZWI1ODRlNzM1YmExN2UzZjZiNzA1YmUyMmU0NzM4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z3gwhn8CBNNAzuS8E9fzAeX8G21KRXAjovY9bRZ3MqM)

Take a look at [CHANGELOG.md](https://github.com/rayenghanmi/RyTuneX/blob/main/CHANGELOG.md#06)

**Comment by rayenghanmi** [comment]
Fixed in [Version 0.6](https://github.com/rayenghanmi/RyTuneX/releases/tag/v0.6.0).
