### ISSUE TITLE
Shortcut issues

### ISSUE THREAD

**Issue by asterriya** [rayenghanmi/RyTuneX#4]
I installed the app from the official release page with admin rights, but the shortcut doesn't appear at all. No errors thou during installation appeared. Win 10x64, last version with all updates.

**Comment by rayenghanmi** [comment]
> I installed the app from the official release page with admin rights, but the shortcut doesn't appear at all. No errors thou during installation appeared. Win 10x64, last version with all updates.

Do you mean, it doesn't appear in the start menu or in the Desktop?
Try typing `RyTuneX` in the search box in the taskbar.

**Comment by asterriya** [comment]
Yeah. It shortcut doesn't appear anywhere after installation.

пт, 5 янв. 2024 г., 11:24 Rayen Ghanmi ***@***.***>:

**Comment by rayenghanmi** [comment]
@asterriya 
Can you answer these:
- What is your Windows 10 build?
- Did you get a popup saying `Installation completed successfully!` ?
- Verify that the package is not installed on your system:
run the following powershell:
`Get-AppxPackage -AllUsers | Where-Object { $_.Name -eq '593c7ba8-f1c9-47cf-a952-7c22b10aac3a' }`
If you got no output, that means the package is not installed on your device.

Please provide me with the answers to the questions so I can identify the problem.

**Comment by asterriya** [comment]
Win 10x64 and yes I get pop-up message about successfully installed
software. No I dont have defenders or any antivirus.

пт, 5 янв. 2024 г., 16:43 Rayen Ghanmi ***@***.***>:

**Comment by rayenghanmi** [comment]
@asterriya
Did you run:
`Get-AppxPackage -AllUsers | Where-Object { $_.Name -eq '593c7ba8-f1c9-47cf-a952-7c22b10aac3a' }`
Any outputs?

**Comment by asterriya** [comment]
Yes, I did.  No outputs

пт, 5 янв. 2024 г., 17:13 Rayen Ghanmi ***@***.***>:

**Comment by rayenghanmi** [comment]
@asterriya 
Can you send your system logs from the event viewer as a txt file?
![EventViewer](https://github.com/rayenghanmi/RyTuneX/assets/108760398/b8836696-5577-4c91-935b-fbd52b3e2847)

**Comment by asterriya** [comment]
I don have it.

пт, 5 янв. 2024 г., 17:54 Rayen Ghanmi ***@***.***>:

**Comment by rayenghanmi** [comment]
@asterriya 
Type `Event Viewer` in the windows search and open it, then locate the System logs, right click on it and `Save All Events As...`
Choose where you want to save the file and its type, then send me the saved file.

**Comment by asterriya** [comment]
I know where is it and how must look like. But it's turned off due privacy
reason. And I'm wouldn't turn it on.

пт, 5 янв. 2024 г., 18:39 Rayen Ghanmi ***@***.***>:

**Comment by rayenghanmi** [comment]
@asterriya 
With such limited information, I'm unable to identify the problem.
