### ISSUE TITLE
impossible to execute setup.exe

### ISSUE THREAD

**Issue by luckyizl** [rayenghanmi/RyTuneX#6]
impossible to execute setup.exe
windows 11 23h2

**Comment by rayenghanmi** [comment]
> impossible to execute setup.exe windows 11 23h2

Is there any specific error popups, or any messages?

**Comment by DaniilBaida** [comment]
Happens to me as well, i try to open but nothing happens

**Comment by rayenghanmi** [comment]
> Happens to me as well, i try to open but nothing happens

Which version of Windows are you currently using?

**Comment by rayenghanmi** [comment]
@DaniilBaida @luckyizl 
I found out what was causing the issue and I'll release the fixed version soon..

**Comment by rayenghanmi** [comment]
> @DaniilBaida @luckyizl I found out what was causing the issue and I'll release the fixed version soon..

This issue has been resolved in [version 0.7.2](../releases/tag/v0.7.2)
