### ISSUE TITLE
App Doesn't Launch

### ISSUE THREAD

**Issue by epeuu** [rayenghanmi/RyTuneX#8]
After successfully installing the app, I've encountered an issue where it fails to launch despite repeated attempts.
Even after restarting my Windows system, the problem persists. 
I've ensured that Windows Defender isn't blocking the app, and I've even downloaded and installed the latest version. 
nterestingly, during the installation process, I noticed a minor typo – "desgin" instead of "design". 
I'll attach a screenshot below for reference. 
My system is currently running `Windows 11 Version 23H2 (OS Build 22631.3374)`.

typo:
![rytunex](https://github.com/rayenghanmi/RyTuneX/assets/86723533/a0f7ecf1-fe27-49fa-b84e-7760d0bb6504)

**Comment by rayenghanmi** [comment]
> After successfully installing the app, I've encountered an issue where it fails to launch despite repeated attempts. Even after restarting my Windows system, the problem persists. I've ensured that Windows Defender isn't blocking the app, and I've even downloaded and installed the latest version. nterestingly, during the installation process, I noticed a minor typo – "desgin" instead of "design". I'll attach a screenshot below for reference. My system is currently running `Windows 11 Version 23H2 (OS Build 22631.3374)`.
> 
> typo: ![rytunex](https://private-user-images.githubusercontent.com/86723533/319760877-a0f7ecf1-fe27-49fa-b84e-7760d0bb6504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjk1NDgsIm5iZiI6MTcxMjI2OTI0OCwicGF0aCI6Ii84NjcyMzUzMy8zMTk3NjA4NzctYTBmN2VjZjEtZmUyNy00OWZhLWI4NGUtNzc2MGQwYmI2NTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDIyMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTQ5NDI0OWIzNjE1Njc4MTk1YzZmMjMzMGY2ZjE2ZTYwYmVhNmY0OTQ3MDcwMDRkODVjMTA0OTE1YjJiZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aw2TXUeqpuMTJPF9WdNvcM42kzNgNQZ8Cot2Uveqp1A)

Can you share what does the event viewer logs in `Windows Logs -> Application` after trying to run the app?

**Comment by epeuu** [comment]
```
Faulting application name: RyTuneX.exe, version: 1.0.0.0, time stamp: 0x65cd0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3374, time stamp: 0x26f62521
Exception code: 0xe0434352
Fault offset: 0x001496a2
Faulting process id: 0x0x1370
Faulting application start time: 0x0x1DA8745E6F36177
Faulting application path: C:\Program Files\WindowsApps\Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r\RyTuneX.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7d530f86-c86c-4e37-9311-0ea62244da72
Faulting package full name: Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r
Faulting package-relative application ID: App


Application: RyTuneX.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found.

Element not found.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics2Methods.Initialize(IObjectReference _obj, DeploymentInitializeOptions deploymentInitializeOptions)
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.Initialize(DeploymentInitializeOptions deploymentInitializeOptions)
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK()
   at .cctor()
   --- End of inner exception stack trace ---

```

**Comment by rayenghanmi** [comment]
> > Can you share what does the event viewer logs in `Windows Logs -> Application` after trying to run the app?
> 
> ```
> Faulting application name: RyTuneX.exe, version: 1.0.0.0, time stamp: 0x65cd0000
> Faulting module name: KERNELBASE.dll, version: 10.0.22621.3374, time stamp: 0x26f62521
> Exception code: 0xe0434352
> Fault offset: 0x001496a2
> Faulting process id: 0x0x1370
> Faulting application start time: 0x0x1DA8745E6F36177
> Faulting application path: C:\Program Files\WindowsApps\Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r\RyTuneX.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: 7d530f86-c86c-4e37-9311-0ea62244da72
> Faulting package full name: Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r
> Faulting package-relative application ID: App
> 
> 
> Application: RyTuneX.exe
> CoreCLR Version: 8.0.324.11423
> .NET Version: 8.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
>  ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found.
> 
> Element not found.
> 
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics2Methods.Initialize(IObjectReference _obj, DeploymentInitializeOptions deploymentInitializeOptions)
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.Initialize(DeploymentInitializeOptions deploymentInitializeOptions)
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK()
>    at .cctor()
>    --- End of inner exception stack trace ---
> ```

Can you confirm if the app opens after installing [.NET Desktop Runtime 3.1.32](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.32-windows-x86-installer)

**Comment by epeuu** [comment]
>Can you confirm if the app opens after installing [.NET Desktop Runtime 8.0.3](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.3-windows-x86-installer)

Once more, I had it previously installed, but in the event of a reinstallation, if errors were to arise once more...

```
**Event 1000, Application Error**  

Faulting application name: RyTuneX.exe, version: 1.0.0.0, time stamp: 0x65cd0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3374, time stamp: 0x26f62521
Exception code: 0xe0434352
Fault offset: 0x001496a2
Faulting process id: 0x0x2140
Faulting application start time: 0x0x1DA880F5E78F129
Faulting application path: C:\Program Files\WindowsApps\Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r\RyTuneX.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 679606e0-4d06-4d47-bf12-5c9fe7a721c2
Faulting package full name: Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r
Faulting package-relative application ID: App
```
```
**Event 1026, .NET Runtime**

Application: RyTuneX.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found.

Element not found.

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics2Methods.Initialize(IObjectReference _obj, DeploymentInitializeOptions deploymentInitializeOptions)
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.Initialize(DeploymentInitializeOptions deploymentInitializeOptions)
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK()
   at .cctor()
   --- End of inner exception stack trace ---



```

**Comment by rayenghanmi** [comment]
> > Can you confirm if the app opens after installing [.NET Desktop Runtime 8.0.3](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.3-windows-x86-installer)
> 
> Once more, I had it previously installed, but in the event of a reinstallation, if errors were to arise once more...
> 
> ```
> **Event 1000, Application Error**  
> 
> Faulting application name: RyTuneX.exe, version: 1.0.0.0, time stamp: 0x65cd0000
> Faulting module name: KERNELBASE.dll, version: 10.0.22621.3374, time stamp: 0x26f62521
> Exception code: 0xe0434352
> Fault offset: 0x001496a2
> Faulting process id: 0x0x2140
> Faulting application start time: 0x0x1DA880F5E78F129
> Faulting application path: C:\Program Files\WindowsApps\Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r\RyTuneX.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: 679606e0-4d06-4d47-bf12-5c9fe7a721c2
> Faulting package full name: Rayen.RyTuneX_0.7.2.0_x86__x747x19506z9r
> Faulting package-relative application ID: App
> ```
> 
> ```
> **Event 1026, .NET Runtime**
> 
> Application: RyTuneX.exe
> CoreCLR Version: 8.0.324.11423
> .NET Version: 8.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
>  ---> System.Runtime.InteropServices.COMException (0x80070490): Element not found.
> 
> Element not found.
> 
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
>    at ABI.Microsoft.Windows.ApplicationModel.WindowsAppRuntime.IDeploymentManagerStatics2Methods.Initialize(IObjectReference _obj, DeploymentInitializeOptions deploymentInitializeOptions)
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManager.Initialize(DeploymentInitializeOptions deploymentInitializeOptions)
>    at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK()
>    at .cctor()
>    --- End of inner exception stack trace ---
> ```

Uninstall the app if it's installed on your device and try [this one](https://drive.google.com/file/d/1Sp1I5obiYxWk7y-tlF6Ju4E4sY6x9CkD/view?usp=drive_link)

**Comment by rayenghanmi** [comment]
> Thank you for your help, my friend. The version you posted works perfectly. Below, I'll share a picture so you can see that everything is functioning smoothly upon the initial launch. Additionally, my apologies for the delayed reply.
> 
> ![Screenshot (21)](https://private-user-images.githubusercontent.com/86723533/321242588-c402ec0c-0d1b-4b58-863a-c2d80e208485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mjc3MTksIm5iZiI6MTcxMjgyNzQxOSwicGF0aCI6Ii84NjcyMzUzMy8zMjEyNDI1ODgtYzQwMmVjMGMtMGQxYi00YjU4LTg2M2EtYzJkODBlMjA4NDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZTYzZWJlMmM0NjI3NmQ4YjUxNzBkNTBkNmZjYTNkYTQ2NTFkMzAzZmExODAxODI5Y2M0N2U1YWI3NjJkZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oKxpXr0NdEFAycVQ3esFI0dOEA8wlhco7N_2tcQAm0w)

That's good, I'm going to close close this issue as the fix will be released in the next version.
